plugin:
  # Players will see their mather language if supported. Otherwise language will be default-language.
  use-player-locale: true
  # See this page https://minecraft.gamepedia.com/Language
  default-language: "en_us"

prisoners:
  # Allow prisoners to speak or hear
  can-speak: true
  can-hear: true

jails:
  # All default values for jails can be modified on jails.yml or with /jw config <jail_name>
  # Default value for number of blocks prisoner have to break (when not defined with /jw config)
  default-max-punishment-blocks: 500

  # Default value for speed-spawn for blocks on jails (seconds)
  block-spawn-speed: 2

  # Allowed commands for all jails. You can add allowed commands per jail with /jw allowedcommand jail command1 command2 ...
  # But, this section cannot be modified with command.
  global-allowed-commands:
    - "/jailworker info"
    - "/jw info"