name: ${project.artifactId}
version: ${project.version}
main: fr.alienationgaming.jailworker.JailWorker
softdepends: [LunaChat, WorldEdit]
api-version: "1.14"
commands:
  jailworker:
    description: Base command of this plugin.
    aliases: ["jail", "jw"]

permissions:
  jailworker.*:
    description: Gives access to everything.
    children:
      jailworker.command.*: true
      jailworker.bypass.*: true
    default: op
  jailworker.command.*:
    description: Give access to all commands.
    children:
      jailworker.command.create: true
      jailworker.command.start.*: true
      jailworker.command.stop.*: true
      jailworker.command.edit.*: true
      jailworker.command.delete.*: true
      jailworker.command.restart.*: true
      jailworker.command.allowed-command.*: true
      jailworker.command.put.*: true
      jailworker.command.free: true
      jailworker.command.clean.*: true
      jailworker.command.list: true
      jailworker.command.info.*: true
      jailworler.command.goto.*: true
      jailworker.command.give.*: true
      jailworker.command.change-point: true
    default: op
  jailworker.bypass.*:
    description: Give ability to bypass all limits.
    children:
      jailworker.bypass.blockedit.*: true
      jailworker.bypass.allowedcommand.*: true
    default: op

# group recommended perms
  jailworker.admin:
    description: Give access to admin commands for administrators.
    children:
      jailworker.command.create: true
      jailworker.command.start: true
      jailworker.command.stop: true
      jailworker.command.config: true
      jailworker.command.delete: true
      jailworker.command.restart: true
      jailworker.command.allowed-command: true
      jailworker.command.reload: true
      jailworker.mod: true
    default: op
  jailworker.mod:
    description: Give access to utils commands for moderators
    children:
      jailworker.command.put.*: true
      jailworker.command.free: true
      jailworker.command.clean: true
      jailworker.command.list: true
      jailworker.command.info: true
      jailworler.command.goto: true
      jailworker.command.give: true
      jailworker.command.change-point: true
      jailworker.bypass.blockedit: true
      jailworker.bypass.allowed-command: true