name: ${project.artifactId}
version: ${project.version}
main: fr.alienationgaming.jailworker.JailWorker
softdepends: [LunaChat, WorldEdit]
api-version: "1.14"
commands:
  jailworker:
    description: Base command of this plugin.
    aliases: ["jail", "jw"]

permissions:
  jailworker.*:
    description: Gives access to everything.
    children:
      jailworker.command.*: true
      jailworker.bypass.*: true
    default: op
  jailworker.command.*:
    description: Give access to all commands.
    children:
      jailworker.command.create: true
      jailworker.command.start.*: true
      jailworker.command.stop.*: true
      jailworker.command.edit.*: true
      jailworker.command.delete.*: true
      jailworker.command.restart.*: true
      jailworker.command.allowed-command.*: true
      jailworker.command.put.*: true
      jailworker.command.free: true
      jailworker.command.clean.*: true
      jailworker.command.list: true
      jailworker.command.info.*: true
      jailworler.command.goto.*: true
      jailworker.command.give.*: true
      jailworker.command.punish-point: true
    default: op
  jailworker.command.info.*:
    description: Give access to all info arguments.
    children:
      jailworker.command.info.jail.*: true
      jailworker.command.info.prisoner: true
      jailworker.command.info.punishment-blocks: true
    default: op
  jailworker.command.info.jail.*:
    default: false
  jailworker.command.info.prisoner:
    default: true
  jailworker.command.info.punishment-blocks:
    default: true
  jailworker.command.goto.*:
    default: true
  jailworker.bypass.*:
    description: Give ability to bypass all limits.
    children:
      jailworker.bypass.block-edit.*: true
      jailworker.bypass.allowed-command.*: true
    default: op
