name: ${project.artifactId}
version: ${project.version}
main: fr.alienationgaming.jailworker.JailWorker
softdepends: [LunaChat, Vault]
api-version: "1.14"
commands:
  jailworker:
    description: Base command of this plugin.
    aliases: ["jail", "jw"]
    usage: /jailworker <subcommand> [arg1] [arg2] ...

permissions:
  jailworker.*:
    description: Gives access to all jailworker commands
    children:
      jailworker.put: true
      jailworker.free: true
      jailworker.create: true
      jailworker.start: true
      jailworker.stop: true
      jailworker.clean: true
      jailworker.config: true
      jailworker.list: true
      jailworker.delete: true
      jailworker.restart: true
      jailworker.info: true
      jailworker.goto: true
      jailworker.give: true
      jailworker.whitecmd: true
      jailworker.reload: true
      jailworker.increase: true
      jailworker.manageowners: true
      jailworker.admin: true
    default: op
  jailworker.mod:
    description: Give access to utils commands for moderators
    children:
      jailworker.put: true
      jailworker.free: true
      jailworker.clean: true
      jailworker.list: true
      jailworker.info: true
      jailworler.goto: true
      jailworker.give: true
      jailworker.increase: true